### Get All Users
GET http://localhost:3001/users

### Get one user
GET http://localhost:3001/users/6399deab864e17c1ef1dd854

### POST One
POST http://localhost:3001/users
Content-Type: application/json

{
    "lastName": "Clausqqq",
    "firstName": "Santa",
    "dateOfBirth": "1998-03-31T00:00:00.000Z",
    "address1": "1457 London Rd",
    "address2": "The Secret Place",
    "city": "Sarnia",
    "postalCode": "1225",
    "country": "Canada",
    "phoneNumber": 20221225,
    "email": "santa@yuting.com",
    "userNotes": "HOHOHO, Merry Christmas!"
}

### DELETE One
DELETE http://localhost:3001/users/6399deab864e17c1ef1dd854

### PUT One
PATCH  http://localhost:3001/users/6397dd9f1fa2213e92744d0f
Content-Type: application/json

{
    "lastName": "The Frog"
}